name: linting, testing, building

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.21.3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install modules
        run: npm install

      - name: Build production project
        run: npm run build:prod

      - name: Linting for ts, js
        run: npm run lint:eslint

      - name: Linting for css, scss
        run: npm run lint:stylelint

      - name: Unit testing
        run: npm run test:unit
